CREATE TABLE project_topic
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(255),
    description        VARCHAR(255),
    is_multiple        BOOLEAN                                 NOT NULL,
    is_reserved        BOOLEAN                                 NOT NULL,
    multiple_max_count INTEGER                                 NOT NULL,
    deadline           TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_project_topic PRIMARY KEY (id)
);

CREATE TABLE project_topic_taken_projects
(
    project_topic_id  BIGINT NOT NULL,
    taken_projects_id BIGINT NOT NULL
);

CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);
INSERT INTO roles (name) VALUES ('USER');
INSERT INTO roles (name) VALUES ('ADMIN');
CREATE TABLE student
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    surname      VARCHAR(255),
    index_number VARCHAR(255),
    user_id      BIGINT,
    CONSTRAINT pk_student PRIMARY KEY (id)
);

CREATE TABLE student_taken_projects
(
    student_id        BIGINT NOT NULL,
    taken_projects_id BIGINT NOT NULL
);

CREATE TABLE taken_project
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deadline         TIMESTAMP WITHOUT TIME ZONE,
    project_topic_id BIGINT,
    student_id       BIGINT,
    file_id          BIGINT,
    CONSTRAINT pk_taken_project PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255),
    password   VARCHAR(255),
    email      VARCHAR(255),
    student_id BIGINT,
    role_id    BIGINT,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE pliki
    ADD description VARCHAR(255);

ALTER TABLE pliki
    ADD taken_project_id BIGINT;

ALTER TABLE project_topic_taken_projects
    ADD CONSTRAINT uc_project_topic_taken_projects_takenprojects UNIQUE (taken_projects_id);

ALTER TABLE student_taken_projects
    ADD CONSTRAINT uc_student_taken_projects_takenprojects UNIQUE (taken_projects_id);

ALTER TABLE pliki
    ADD CONSTRAINT FK_PLIKI_ON_TAKEN_PROJECT FOREIGN KEY (taken_project_id) REFERENCES taken_project (id);

ALTER TABLE student
    ADD CONSTRAINT FK_STUDENT_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE taken_project
    ADD CONSTRAINT FK_TAKEN_PROJECT_ON_FILE FOREIGN KEY (file_id) REFERENCES pliki (id);

ALTER TABLE taken_project
    ADD CONSTRAINT FK_TAKEN_PROJECT_ON_PROJECT_TOPIC FOREIGN KEY (project_topic_id) REFERENCES project_topic (id);

ALTER TABLE taken_project
    ADD CONSTRAINT FK_TAKEN_PROJECT_ON_STUDENT FOREIGN KEY (student_id) REFERENCES student (id);

ALTER TABLE "user"
    ADD CONSTRAINT FK_USER_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);

ALTER TABLE "user"
    ADD CONSTRAINT FK_USER_ON_STUDENT FOREIGN KEY (student_id) REFERENCES student (id);

ALTER TABLE project_topic_taken_projects
    ADD CONSTRAINT fk_protoptakpro_on_project_topic FOREIGN KEY (project_topic_id) REFERENCES project_topic (id);

ALTER TABLE project_topic_taken_projects
    ADD CONSTRAINT fk_protoptakpro_on_taken_project FOREIGN KEY (taken_projects_id) REFERENCES taken_project (id);

ALTER TABLE student_taken_projects
    ADD CONSTRAINT fk_stutakpro_on_student FOREIGN KEY (student_id) REFERENCES student (id);

ALTER TABLE student_taken_projects
    ADD CONSTRAINT fk_stutakpro_on_taken_project FOREIGN KEY (taken_projects_id) REFERENCES taken_project (id);